#pragma once 

#define FHMSG_ERR_FREE (0)
#define FHMSG_ERR_BASE (0x0a000000)
#define FHMSG_ERR_NULL (FHMSG_ERR_BASE + 1)
#define FHMSG_ERR_BUFFSIZE (FHMSG_ERR_BASE + 2)
#define FHMSG_ERR_FORMAT (FHMSG_ERR_BASE + 3) 
#define FHMSG_ERR_RANGE (FHMSG_ERR_BASE + 4)